# First build both the backend and frontend images using the respective Dockerfiles, then use this docker-compose file to run the application.
# The tester just needs to run "docker-compose up -d" in the terminal to start both the backend and frontend services.
# Guide: Install Docker Desktop, put this file in any folder, open terminal in that folder and run docker compose up -d, then open http://localhost"
services:

  backend:
    image: adityaroy0804/insurance-backend:latest
    container_name: insurance_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  frontend:
    image: adityaroy0804/insurance-frontend:latest
    container_name: insurance_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy